global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'anypoint-mq-exporter'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['anypoint-mq-prometheus-exporter-production.up.railway.app']
    scheme: https
